### ISSUE TITLE
Unable to Load ConvLLaVA pretrained model

### ISSUE THREAD

**Issue by rotem154154** [alibaba/conv-llava#3]
I am trying to load the ConvLLaVA/ConvLLaVA-sft-768 model using the transformers library, but I am encountering an error related to a missing preprocessor_config.json file. Here is the code snippet I am using:

```python
from transformers import AutoProcessor, AutoModelForCausalLM

processor = AutoProcessor.from_pretrained("ConvLLaVA/ConvLLaVA-sft-768")
model = AutoModelForCausalLM.from_pretrained("ConvLLaVA/ConvLLaVA-sft-768")
```
Error:
`OSError: ConvLLaVA/ConvLLaVA-sft-768 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/ConvLLaVA/ConvLLaVA-sft-768/tree/main' for available files.`

Could you please look into this issue and provide the necessary file or guidance on how to resolve this?

**Comment by John-Ge** [comment]
Hello, we do not specially define a preprocessor for ConvLLaVA model, we directly use the image processor of CLIP-ConvNeXt, please modify your code by:

`processor = AutoProcessor.from_pretrained("ConvLLaVA/ConvLLaVA-ConvNeXt-768")
`

Please try it.

**Comment by rotem154154** [comment]
Hello,

Thank you for your assistance with the processor. Using AutoProcessor.from_pretrained("ConvLLaVA/ConvLLaVA-ConvNeXt-768") works fine. However, I am still encountering an issue when trying to load the model.

Here is the modified code snippet and the resulting error:

```python
from transformers import AutoProcessor, AutoModelForCausalLM

processor = AutoProcessor.from_pretrained("ConvLLaVA/ConvLLaVA-ConvNeXt-768") 
model = AutoModelForCausalLM.from_pretrained("ConvLLaVA/ConvLLaVA-sft-768")
```

Error:

```
ValueError: Unrecognized configuration class <class transformers.models.convnext.configuration_convnext.ConvNextConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, LlamaConfig, CodeGenConfig, CohereConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DbrxConfig, ElectraConfig, ErnieConfig, FalconConfig, FuyuConfig, GemmaConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, JambaConfig, JetMoeConfig, LlamaConfig, MambaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MistralConfig, MixtralConfig, MptConfig, MusicgenConfig, MusicgenMelodyConfig, MvpConfig, OlmoConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PersimmonConfig, PhiConfig, Phi3Config, PLBartConfig, ProphetNetConfig, QDQBertConfig, Qwen2Config, Qwen2MoeConfig, RecurrentGemmaConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, StableLmConfig, Starcoder2Config, TransfoXLConfig, TrOCRConfig, WhisperConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```
It appears that AutoModelForCausalLM is not recognizing the configuration class for the ConvNeXt model. Could you provide guidance on how to properly load the model, or if there is a different model class I should use?

Thank you for your help.

**Comment by John-Ge** [comment]
OK, you could use the CLIPImageProcessor to load the image processor:

`
image_processor = CLIPImageProcessor.from_from_pretrained("ConvLLaVA/ConvLLaVA-ConvNeXt-768") 
`

We recommand you to install our repo and call the function : [load pretrained model](https://github.com/alibaba/conv-llava/blob/ef8fcd718f651a573c1347d7cede15db65fae4d4/llava/model/builder.py#L27) to load our model.

Thank you for your interest in our work.
