### ISSUE TITLE
Size mismatch in convnext

### ISSUE THREAD

**Issue by zhiyuanyou** [alibaba/conv-llava#4]
Hello,

Thanks for your great work!

I notice that in your released weights (https://huggingface.co/ConvLLaVA/LAION-CLIP-ConvNeXt-Large-512), the shape of `model.vision_tower.vision_tower.layernorm.weight` and `model.vision_tower.vision_tower.layernorm.bias` are both `torch.Size([3072])`. This means that the layernorm layer has been **placed after the added fifth layer** (whose width is 3072). 

However, in your code (https://github.com/alibaba/conv-llava/blob/main/llava/model/multimodal_encoder/convnext_encoder.py), there is **no operation about layernorm**. I print the shape of `vision_tower.layernorm.weight` and `vision_tower.layernorm.bias` in convnext_encoder.py, which are both `torch.Size([1536]`. This means that the layernorm layer is still **placed after the fourth layer** (whose width is 1536). 

Therefore, I wonder whether there are some mistakes in your released code.

**Comment by zhiyuanyou** [comment]
After debug, I found that the weights of `model.vision_tower.vision_tower.layernorm.weight` and `model.vision_tower.vision_tower.layernorm.bias` are **never used in the model**. 

I want to verify whether my understanding is right. If so, removing these two parameters from the released weights will be better.

**Comment by John-Ge** [comment]
Those two parameters are never used in the model. We delete those parameter in https://github.com/alibaba/conv-llava/blob/3f5aee686c0334fc02b0419e2099d140c3188d69/llava/train/train.py#L248-L262 after training. You can delete them. 

Thank you for pointing out  that checkpoint contains the weights of layernorm.
