### ISSUE TITLE
Evaluation on RefCOCO

### ISSUE THREAD

**Issue by jonasjunzhang** [alibaba/conv-llava#5]
Hello, I want to reproduce the results on RefCOCO, RefCOCO+ and RefCOCOg, but I found that VLMEvalKit doesn't support these datasets, and lmms-eval only support REG(Grounded Captioning) evaluation on these datsets. Did you evaluate REC(Visual Grounding) Evaluation results with your own scripts? Thank you!

**Comment by John-Ge** [comment]
Hello, we use the code base of: https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/eval/refcoco/evaluate_grounding.py. While the preprocessing of the bbox of their work and LLaVA are not the same. You could refer to LLaVA and modify above code to evaluate your model.

**Comment by John-Ge** [comment]
I have update the evaluation code:
https://github.com/alibaba/conv-llava/blob/main/scripts/refcoco.sh
You could directly use above code for evaluation.
