### ISSUE TITLE
使用VLMEVALKIT 评测

### ISSUE THREAD

**Issue by Han-jiaxin** [alibaba/conv-llava#8]
当我使用VLMEVALKIT 时，发现您提供的run.py文件中，提及from vlmeval.utils import dataset_URLs, DATASET_TYPE, abbr2full, 以及from vlmeval.evaluate import * 这些我在VLMEVALKIT 的官方文件下没有找到，想问下这个问题该如何解决？

**Comment by John-Ge** [comment]
应该是VLMEVALKIT更新了。你可以用lmms-eval来进行测试。

**Comment by Han-jiaxin** [comment]
好的，非常感谢您的回答

**Comment by Han-jiaxin** [comment]
您好，方便提供refcoco jsonl文件的下载地址吗？

**Comment by John-Ge** [comment]
https://github.com/Vision-CAIR/MiniGPT-4/tree/main/eval_scripts/eval_data

**Comment by Han-jiaxin** [comment]
您好，非常感谢，您的回答很有帮助，另外想问一下，当使用VLMEVALKIT测评时，我们会为convllava在/VLMEvalKit/vlmeval/vlm 下写一个类似模型加载的py文件，您方便提供一下吗？

**Comment by John-Ge** [comment]
使用llava的就可以了，你可以参考我们给的文档进行测试

**Comment by Han-jiaxin** [comment]
当我按照llava的进行测试时，会报错：ValueError: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date. 在测试时，我们输入的llavapath 是第三阶段模型的保存路径吗？

**Comment by Han-jiaxin** [comment]
没事啦，我已经解决了，应该是flash-attention版本的问题。

**Comment by Han-jiaxin** [comment]
您好，当我load 测试工具下/VLMEvalKit/vlmeval/vlm/llava.py 进行测试时，发现测试的结果均为0，我觉得不能直接用这个llava.py,需要根据这个写一个自己的模型文件，但是我在写的过程中，预训练模型以及数据集的加载时仍有问题，希望您可以提供一下相关的文档。非常感谢🙏
